server:
  port: 8080

spring:
  application:
    name: api-gateway

  # =========================
  # Redis Configuration
  # =========================
  redis:
    host: localhost
    port: 6379

  # =========================
  # Spring Cloud Gateway
  # =========================
  cloud:
    gateway:

      # Global filters applied to all routes
      default-filters:
        # Redis-based rate limiter
        - name: RequestRateLimiter
          args:
            redis-rate-limiter.replenishRate: 5     # 5 requests per second
            redis-rate-limiter.burstCapacity: 10    # sudden burst allowed
            key-resolver: "#{@userKeyResolver}"

      routes:
        # =========================
        # Auth Service Route
        # =========================
        - id: auth-service
          uri: http://localhost:8081
          predicates:
            - Path=/auth/**

        # =========================
        # Expense Service Route
        # =========================
        - id: expense-service
          uri: http://localhost:8082
          predicates:
            - Path=/expenses/**

# =========================
# Logging (Very helpful)
# =========================
logging:
  level:
    org.springframework.cloud.gateway: INFO
    reactor.netty.http.client: INFO
