server:
  port: 8082

spring:
  application:
    name: expense-service

  datasource:
    url: jdbc:mysql://mysql:3306/expensedb
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

  redis:
    host: localhost
    port: 6379

logging:
  level:
    org.springframework.security: INFO
    org.springframework.data.redis: INFO

