
server:
  port: 8082

spring:
  application:
    name: expense-service

  # =========================
  # Database Configuration (H2)
  # =========================
 spring:
  datasource:
    url: jdbc:mysql://mysql:3306/expense_db
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false


  # =========================
  # Redis Configuration
  # =========================
  redis:
    host: localhost
    port: 6379

# =========================
# Logging
# =========================
logging:
  level:
    org.springframework.security: INFO
    org.springframework.data.redis: INFO
